name: Auto Tagging

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python & uv
        uses: ./.github/actions/python-setup

      - name: Commitzen version
        id: cz
        run: |
          TAG=$(uv run cz version)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Next version will be $TAG"

      - name: Check if tag exists
        uses: actions/github-script@v8
        env:
          TAG_NAME: v${{ env.TAG }}
        with:
          script: |
            const tag = process.env.TAG_NAME;
            const core = require('@actions/core');

            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
              console.log(`Tag ${tag} already exists.`);
              core.setOutput('exists', 'true');  // set output for later steps
            } catch (error) {
              if (error.status === 404) {
                console.log(`Tag ${tag} does not exist. Will create it.`);
                core.setOutput('exists', 'false');
              } else {
                throw error;
              }
            }
          result-encoding: string
