name: Build & Ship

on:
  workflow_run:
    workflows: ["Auto Tagging"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build-docs:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    outputs:
      docs-path: docs/docsite

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: ./.github/actions/python-setup

      - name: Install Sphinx dependencies
        run: uv run pip install -r build_docsite/requirements.txt

      - name: Build documentation
        run: uv run sphinx-build -b html build_docsite docs/docsite

      - name: Inject HTML docs version
        run: uv run python build/update_docsite_html_version.py docs/docsite

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/docsite
          retention-days: 1

  build-collection:
    needs: build-docs
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: ./.github/actions/python-setup

      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/docsite

      - name: Inject galaxy.yml version
        run: uv run python build/update_galaxy_version.py galaxy.yml

      - name: Generate CHANGELOG
        run: uv run cz changelog --file-name CHANGELOG.md

      - name: Build Ansible collection
        run: uv run ansible-galaxy collection build

      - uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
          name: jewdba-eda-ansible-collection
          path: jewdba-eda-*.tar.gz
          retention-days: 1

  release:
    needs: build-collection
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: ./.github/actions/python-setup

      - name: Commitizen version
        run: |
          TAG=$(uv run cz version)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: jewdba-eda-ansible-collection

      - uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Generate Release CHANGELOG delta
        run: uv run cz changelog --incremental --file-name CHANGELOG_DELTA.md

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          files: |
            jewdba-eda-*.tar.gz
            CHANGELOG.md
          body_path: CHANGELOG_DELTA.md
